apiVersion: v1
kind: Secret
metadata:
  name: storydoc-automation-secrets
  namespace: storydoc-automation
  labels:
    app: storydoc-automation
type: Opaque
data:
  # All values below should be Base64 encoded in a real environment
  # Example: echo -n "value" | base64
  
  # Mailinator API key for email verification
  MAILINATOR_API_KEY: bWFpbGluYXRvci1hcGkta2V5LXBsYWNlaG9sZGVy
  
  # Test user credentials
  TEST_USER_EMAIL: dGVzdC51c2VyQG1haWxpbmF0b3IuY29t
  TEST_USER_PASSWORD: VGVzdEAxMjM=
  
  # Application URLs
  STORYDOC_BASE_URL: aHR0cHM6Ly9lZGl0b3Itc3RhZ2luZy5zdG9yeWRvYy5jb20=
  SELENIUM_HUB_URL: aHR0cDovL3NlbGVuaXVtLWh1YjoxMjM0L3dkL2h1Yg==
  
  # Integration API keys
  REPORT_PORTAL_API_KEY: cmVwb3J0LXBvcnRhbC1hcGkta2V5LXBsYWNlaG9sZGVy
  SLACK_WEBHOOK_URL: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVFhYWFhYWFhYL0JYWFBYWFJYWFBYL3l5eXl5eXl5eXl5eXl5eXl5eXk=
  GITHUB_TOKEN: Z2gtdG9rZW4tcGxhY2Vob2xkZXI=