name: Build Test Automation Framework

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/test/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/test/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('src/test/requirements.txt') }}
        restore-keys: pip-
    
    - name: Install dependencies
      run: pip install -r src/test/requirements.txt
    
    - name: Lint with flake8
      run: pip install flake8 && flake8 src/test --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Check formatting with black
      run: pip install black && black --check src/test
    
    - name: Type checking with mypy
      run: pip install mypy && mypy src/test
    
    - name: Verify package installation
      run: cd src/test && python -c "import pytest; import selenium; import requests; print('Package verification successful')"